import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div style={{ height: "100vh", padding: "20px", backgroundColor: "#232323", color: "white" }}>
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        This project was generated By{" "}
        <a href="https://www.dhiwise.com" style={{ color: "#87CEFA", textDecoration: "none" }}>
          Dhiwise
        </a>
        . Quickly use below links to navigate through all pages.
      </p>
      <ul style={{ listStyle: "none", padding: "0" }}>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomePageOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/homepagetwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
            HomePageTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/sprintgameone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            SprintGameOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/sprintgametwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
            SprintGameTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/audiocallgameone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AudiocallGameOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/audiocallgametwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AudiocallGameTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/classbookone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ClassbookOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/classbooktwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ClassbookTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/statisticsone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            StatisticsOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/statisticstwo" style={{ color: "#87CEFA", textDecoration: "none" }}>
            StatisticsTwo
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/aboutone" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AboutOne
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/audiocallgamefour" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AudiocallGameFour
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/sprintgamethree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            SprintGameThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/audiocallgamethree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AudiocallGameThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/sprintgamefour" style={{ color: "#87CEFA", textDecoration: "none" }}>
            SprintGameFour
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/statisticsthree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            StatisticsThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/classbookthree" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ClassbookThree
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/classbookfour" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ClassbookFour
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/audiocallgamefive" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AudiocallGameFive
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/audiocallgamesix" style={{ color: "#87CEFA", textDecoration: "none" }}>
            AudiocallGameSix
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/frameeighteen" style={{ color: "#87CEFA", textDecoration: "none" }}>
            FrameEighteen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/frameten" style={{ color: "#87CEFA", textDecoration: "none" }}>
            FrameTen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/frametwelve" style={{ color: "#87CEFA", textDecoration: "none" }}>
            FrameTwelve
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/classbookfive" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ClassbookFive
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/classbooksix" style={{ color: "#87CEFA", textDecoration: "none" }}>
            ClassbookSix
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/frame35271" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Frame35271
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/framethirteen" style={{ color: "#87CEFA", textDecoration: "none" }}>
            FrameThirteen
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/frame35272" style={{ color: "#87CEFA", textDecoration: "none" }}>
            Frame35272
          </Link>
        </li>
        <li style={{ marginBottom: "10px" }}>
          <Link to="/frameseventeen" style={{ color: "#87CEFA", textDecoration: "none" }}>
            FrameSeventeen
          </Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
